const interests = [
	"Fast paced music",
	"Dance music",
	"Folk music",
	"Country music",
	"Classical music",
	"Musical",
	"Pop music",
	"Rock music",
	"Metal or Hardrock music",
	"Punk music",
	"Hiphop/ Rap music",
	"Reggae/ Ska music",
	"Swing/ Jazz music",
	"Rock n roll music",
	"Alternative music",
	"Latino music",
	"Techno/ Trance music",
	"Opera music",
	"Horror movie",
	"Thriller movie",
	"Comedy movie",
	"Romantic movie",
	"Sci-fi movie",
	"War movie",
	"Fantasy/Fairy tales movie",
	"Animated movie",
	"Documentary movie",
	"Western movie",
	"Action movie",
	"History",
	"Psychology",
	"Politics",
	"Mathematics",
	"Physics",
	"Internet",
	"PC",
	"Economy Management",
	"Biology",
	"Chemistry",
	"Reading",
	"Geography",
	"Foreign languages",
	"Medicine",
	"Law",
	"Cars",
	"Art exhibitions",
	"Religion",
	"Countryside/ outdoors",
	"Dancing",
	"Musical instruments",
	"Writing",
	"Passive sport",
	"Active sport",
	"Gardening",
	"Celebrities",
	"Shopping",
	"Science and technology",
	"Theatre",
	"Fun with friends",
	"Adrenaline sports",
	"Pets",
];

interests.sort();

module.exports = interests;
